import type { ComponentType, SVGProps } from 'react';
import {
  ApartmentSVG,
  ApartmentsSVG,
  BarrierSVG,
  Blueprint1SVG,
  BlueprintSVG,
  BuildingLevelsSVG,
  BuildingSVG,
  BulldozerSVG,
  CertificateSVG,
  ChainsawSVG,
  ChangeOrderSVG,
  ConcreteMixerSVG,
  ContractSVG,
  Crane1SVG,
  CraneSVG,
  DashboardChartSVG,
  Driller1SVG,
  DrillerSVG,
  DumpTruckSVG,
  ElectricitySVG,
  ExcavatorSVG,
  Fence1SVG,
  FenceSVG,
  ForecastCalendarSVG,
  ForkliftSVG,
  HammerSVG,
  HardHatSVG,
  HelmetSVG,
  HouseKeySVG,
  HouseSVG,
  InvoiceSVG,
  LiftSVG,
  MeasuringTapeSVG,
  NailSVG,
  PaintBrushSVG,
  PipeSVG,
  PliersSVG,
  ProgressReportSVG,
  RoofSVG,
  Saw1SVG,
  Saw2SVG,
  SawSVG,
  ScrewSVG,
  ScrewdriverSVG,
  SecurityIconSVG,
  ShovelSVG,
  SkylineSVG,
  SpatulaSVG,
  SteamrollerSVG,
  TankTruckSVG,
  ToolsSVG,
  TractorSVG,
  TrowelSVG,
  Truck1SVG,
  TruckSVG,
  WallSVG,
  WheelbarrowSVG,
  WrenchSVG,
} from '../../components/svgs';

export interface SvgEntry {
  id: string;
  label: string;
  Component: ComponentType<SVGProps<SVGSVGElement> & { size?: number; colorScheme?: string }>;
  category: 'tools' | 'vehicles' | 'buildings' | 'documents';
}

export const SVG_ENTRIES: SvgEntry[] = [
  // Tools
  { id: 'hard-hat', label: 'Hard Hat', Component: HardHatSVG, category: 'tools' },
  { id: 'helmet', label: 'Helmet', Component: HelmetSVG, category: 'tools' },
  { id: 'hammer', label: 'Hammer', Component: HammerSVG, category: 'tools' },
  { id: 'wrench', label: 'Wrench', Component: WrenchSVG, category: 'tools' },
  { id: 'screwdriver', label: 'Screwdriver', Component: ScrewdriverSVG, category: 'tools' },
  { id: 'pliers', label: 'Pliers', Component: PliersSVG, category: 'tools' },
  { id: 'saw', label: 'Saw', Component: SawSVG, category: 'tools' },
  { id: 'saw-1', label: 'Saw 2', Component: Saw1SVG, category: 'tools' },
  { id: 'saw-2', label: 'Saw 3', Component: Saw2SVG, category: 'tools' },
  { id: 'chainsaw', label: 'Chainsaw', Component: ChainsawSVG, category: 'tools' },
  { id: 'shovel', label: 'Shovel', Component: ShovelSVG, category: 'tools' },
  { id: 'trowel', label: 'Trowel', Component: TrowelSVG, category: 'tools' },
  { id: 'spatula', label: 'Spatula', Component: SpatulaSVG, category: 'tools' },
  { id: 'paint-brush', label: 'Paint Brush', Component: PaintBrushSVG, category: 'tools' },
  { id: 'measuring-tape', label: 'Tape', Component: MeasuringTapeSVG, category: 'tools' },
  { id: 'nail', label: 'Nail', Component: NailSVG, category: 'tools' },
  { id: 'screw', label: 'Screw', Component: ScrewSVG, category: 'tools' },
  { id: 'pipe', label: 'Pipe', Component: PipeSVG, category: 'tools' },
  { id: 'tools', label: 'Tools', Component: ToolsSVG, category: 'tools' },
  { id: 'barrier', label: 'Barrier', Component: BarrierSVG, category: 'tools' },
  { id: 'electricity', label: 'Electricity', Component: ElectricitySVG, category: 'tools' },
  { id: 'fence', label: 'Fence', Component: FenceSVG, category: 'tools' },
  { id: 'fence-1', label: 'Fence 2', Component: Fence1SVG, category: 'tools' },

  // Vehicles
  { id: 'crane', label: 'Crane', Component: CraneSVG, category: 'vehicles' },
  { id: 'crane-1', label: 'Crane 2', Component: Crane1SVG, category: 'vehicles' },
  { id: 'excavator', label: 'Excavator', Component: ExcavatorSVG, category: 'vehicles' },
  { id: 'bulldozer', label: 'Bulldozer', Component: BulldozerSVG, category: 'vehicles' },
  { id: 'dump-truck', label: 'Dump Truck', Component: DumpTruckSVG, category: 'vehicles' },
  { id: 'forklift', label: 'Forklift', Component: ForkliftSVG, category: 'vehicles' },
  { id: 'concrete-mixer', label: 'Mixer', Component: ConcreteMixerSVG, category: 'vehicles' },
  { id: 'steamroller', label: 'Steamroller', Component: SteamrollerSVG, category: 'vehicles' },
  { id: 'tank-truck', label: 'Tank Truck', Component: TankTruckSVG, category: 'vehicles' },
  { id: 'tractor', label: 'Tractor', Component: TractorSVG, category: 'vehicles' },
  { id: 'truck', label: 'Truck', Component: TruckSVG, category: 'vehicles' },
  { id: 'truck-1', label: 'Truck 2', Component: Truck1SVG, category: 'vehicles' },
  { id: 'driller', label: 'Driller', Component: DrillerSVG, category: 'vehicles' },
  { id: 'driller-1', label: 'Driller 2', Component: Driller1SVG, category: 'vehicles' },
  { id: 'lift', label: 'Lift', Component: LiftSVG, category: 'vehicles' },
  { id: 'wheelbarrow', label: 'Wheelbarrow', Component: WheelbarrowSVG, category: 'vehicles' },

  // Buildings
  { id: 'building', label: 'Building', Component: BuildingSVG, category: 'buildings' },
  { id: 'apartment', label: 'Apartment', Component: ApartmentSVG, category: 'buildings' },
  { id: 'apartments', label: 'Apartments', Component: ApartmentsSVG, category: 'buildings' },
  { id: 'house', label: 'House', Component: HouseSVG, category: 'buildings' },
  { id: 'house-key', label: 'House Key', Component: HouseKeySVG, category: 'buildings' },
  { id: 'skyline', label: 'Skyline', Component: SkylineSVG, category: 'buildings' },
  { id: 'roof', label: 'Roof', Component: RoofSVG, category: 'buildings' },
  { id: 'wall', label: 'Wall', Component: WallSVG, category: 'buildings' },
  { id: 'building-levels', label: 'Levels', Component: BuildingLevelsSVG, category: 'buildings' },
  { id: 'blueprint', label: 'Blueprint', Component: BlueprintSVG, category: 'buildings' },
  { id: 'blueprint-1', label: 'Blueprint 2', Component: Blueprint1SVG, category: 'buildings' },

  // Documents
  { id: 'contract', label: 'Contract', Component: ContractSVG, category: 'documents' },
  { id: 'invoice', label: 'Invoice', Component: InvoiceSVG, category: 'documents' },
  { id: 'certificate', label: 'Certificate', Component: CertificateSVG, category: 'documents' },
  { id: 'change-order', label: 'Change Order', Component: ChangeOrderSVG, category: 'documents' },
  { id: 'progress-report', label: 'Report', Component: ProgressReportSVG, category: 'documents' },
  { id: 'dashboard-chart', label: 'Chart', Component: DashboardChartSVG, category: 'documents' },
  { id: 'forecast', label: 'Forecast', Component: ForecastCalendarSVG, category: 'documents' },
  { id: 'security', label: 'Security', Component: SecurityIconSVG, category: 'documents' },
];

export const CATEGORIES = ['tools', 'vehicles', 'buildings', 'documents'] as const;
