import type { TicketType } from '../types';

export const TICKET_TYPES: TicketType[] = [
  {
    type: 'Epic',
    icon: 'zap',
    color: '#9F7AEA',
    titleConvention: 'PROJECT: Epic Title',
    example: 'iPPMech: Bid Board',
    requiredFields: [
      'Summary',
      'Vision',
      'Problem Statement',
      'Goals',
      'Success Metrics',
      'Scope (In/Out)',
      'Timeline',
      'Stakeholders',
      'Dependencies',
      'Risks',
      'Acceptance Criteria',
    ],
    estimate: 'No estimate on Epics',
    labels: 'epic, [project-name], [quarter]',
    warningRule: '10-Week Warning: If >10 weeks, check if it should be a Project',
  },
  {
    type: 'Story',
    icon: 'filetext',
    color: '#48BB78',
    titleConvention: 'Clear action statement',
    example: 'Add filter by trade to crew schedule view',
    requiredFields: [
      'User Story (As a / I want / So that)',
      'Acceptance Criteria (Given/When/Then)',
      'Design links',
      'Technical Notes',
      'Definition of Done',
    ],
    estimate: '1 point = 1 hour',
    labels: 'Per parent epic',
    warningRule: 'Must have AC — no exceptions',
  },
  {
    type: 'Bug',
    icon: 'bug',
    color: '#F56565',
    titleConvention: '[Area]: Broken behavior',
    example: 'MFR: Total column shows NaN when cost code is empty',
    requiredFields: [
      'Summary',
      'Environment',
      'Steps to Reproduce',
      'Expected vs Actual',
      'Evidence (screenshots/logs)',
      'Reproducibility',
      'Severity (P0-P3)',
      'Fix Acceptance Criteria',
    ],
    estimate: 'Varies by severity',
    labels: 'bug, [severity]',
    warningRule: 'P0 = drop everything. P1 = fix this sprint.',
  },
  {
    type: 'Task',
    icon: 'clipboard',
    color: '#4299E1',
    titleConvention: 'Technical action verb',
    example: 'Set up database migration for bid board tables',
    requiredFields: [
      'What (implementation step)',
      'Why (what it enables)',
      'Technical Details',
      'Definition of Done',
      'Dependencies',
    ],
    estimate: '1-8 points typically',
    labels: 'Per parent',
    warningRule: 'Same template for Tasks and Sub-tasks',
  },
  {
    type: 'Spike',
    icon: 'search',
    color: '#ECC94B',
    titleConvention: 'Prefixed with [Spike]',
    example: '[Spike] Evaluate PDF renderer libraries for report export',
    requiredFields: [
      'Research Question',
      'Time Box',
      'Deliverable Checklist',
      'Research Plan',
      'Success Criteria',
    ],
    estimate: 'Time-boxed',
    labels: 'spike, [area]',
    warningRule: 'Must have a time box and defined deliverable',
  },
];
