// Dashboard/business SVGs (ported from ppmportal-client)
export { default as DashboardChartSVG } from './DashboardChartSVG';
export { default as ForecastCalendarSVG } from './ForecastCalendarSVG';
export { default as ChangeOrderSVG } from './ChangeOrderSVG';
export { default as ProgressReportSVG } from './ProgressReportSVG';
export { default as InvoiceSVG } from './InvoiceSVG';
export { default as BuildingLevelsSVG } from './BuildingLevelsSVG';
export { default as HardHatSVG } from './HardHatSVG';
export { default as CertificateSVG } from './CertificateSVG';
export { default as SecurityIconSVG } from './SecurityIconSVG';

// Construction/architecture SVGs
export { default as ApartmentSVG } from './ApartmentSVG';
export { default as ApartmentsSVG } from './ApartmentsSVG';
export { default as BarrierSVG } from './BarrierSVG';
export { default as Blueprint1SVG } from './Blueprint1SVG';
export { default as BlueprintSVG } from './BlueprintSVG';
export { default as BuildingSVG } from './BuildingSVG';
export { default as BulldozerSVG } from './BulldozerSVG';
export { default as ChainsawSVG } from './ChainsawSVG';
export { default as ConcreteMixerSVG } from './ConcreteMixerSVG';
export { default as ContractSVG } from './ContractSVG';
export { default as Crane1SVG } from './Crane1SVG';
export { default as CraneSVG } from './CraneSVG';
export { default as Driller1SVG } from './Driller1SVG';
export { default as DrillerSVG } from './DrillerSVG';
export { default as DumpTruckSVG } from './DumpTruckSVG';
export { default as ElectricitySVG } from './ElectricitySVG';
export { default as ExcavatorSVG } from './ExcavatorSVG';
export { default as Fence1SVG } from './Fence1SVG';
export { default as FenceSVG } from './FenceSVG';
export { default as ForkliftSVG } from './ForkliftSVG';
export { default as HammerSVG } from './HammerSVG';
export { default as HelmetSVG } from './HelmetSVG';
export { default as HouseKeySVG } from './HouseKeySVG';
export { default as HouseSVG } from './HouseSVG';
export { default as LiftSVG } from './LiftSVG';
export { default as MeasuringTapeSVG } from './MeasuringTapeSVG';
export { default as NailSVG } from './NailSVG';
export { default as PaintBrushSVG } from './PaintBrushSVG';
export { default as PipeSVG } from './PipeSVG';
export { default as PlaceholderSVG } from './PlaceholderSVG';
export { default as PliersSVG } from './PliersSVG';
export { default as RoofSVG } from './RoofSVG';
export { default as Saw1SVG } from './Saw1SVG';
export { default as Saw2SVG } from './Saw2SVG';
export { default as SawSVG } from './SawSVG';
export { default as ScrewSVG } from './ScrewSVG';
export { default as ScrewdriverSVG } from './ScrewdriverSVG';
export { default as ShovelSVG } from './ShovelSVG';
export { default as SkylineSVG } from './SkylineSVG';
export { default as SpatulaSVG } from './SpatulaSVG';
export { default as SteamrollerSVG } from './SteamrollerSVG';
export { default as TankTruckSVG } from './TankTruckSVG';
export { default as ToolsSVG } from './ToolsSVG';
export { default as TractorSVG } from './TractorSVG';
export { default as TrowelSVG } from './TrowelSVG';
export { default as Truck1SVG } from './Truck1SVG';
export { default as TruckSVG } from './TruckSVG';
export { default as WallSVG } from './WallSVG';
export { default as WheelbarrowSVG } from './WheelbarrowSVG';
export { default as WrenchSVG } from './WrenchSVG';

export { getColor } from './colors';
export type { ColorScheme } from './colors';
